# Generated by Django 5.0.2 on 2024-02-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_students_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationSchool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('grade', models.CharField(max_length=2)),
            ],
        ),
    ]
